services:
  app:
    environment:
      OPEN_API_KEY: ${OPEN_API_KEY}
      BLOB_SAS_TOKEN: ${BLOB_SAS_TOKEN}
      BLOB_SAS_URL: ${BLOB_SAS_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SERVER: ${DB_SERVER}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
      FIREBASE_ENCODED_AUTH: ${FIREBASE_ENCODED_AUTH}
      TELEGRAM_BOT_KEY: ${TELEGRAM_BOT_KEY}
    volumes:
      - ./deployments:/opt/payara/appserver/glassfish/domains/domain1/autodeploy
    ports:
      - "8080:8080"
      - "4848:4848"
      - "9009:9009"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8080/health/ready || exit 1
    build:
      context: .
      dockerfile: Dockerfile
    image: fish.payara/jee-gpt:${APP_IMAGE_TAG:-latest}
#    depends_on:
#      - telemetry
    networks:
      - telemetry-network

#  telemetry:
#    image: docker.io/grafana/otel-lgtm:latest
#    container_name: lgtm
#    ports:
#      - "3000:3000"  # Grafana UI
#      - "4317:4317"  # OTLP gRPC
#      - "4318:4318"  # OTLP HTTP
#    volumes:
#      - ./container/grafana:/data/grafana
#      - ./container/prometheus:/data/prometheus
#      - ./container/loki:/loki
#    environment:
#      - GF_PATHS_DATA=/data/grafana
#    restart: always
#    networks:
#      - telemetry-network


networks:
  telemetry-network:
    driver: bridge